const po_activity_type = {
  CREATE_PO: "Create PO",
  SUBMIT_PO: "PO Submitted",
  FAILURE_PO: "Failed To Update",
  UPDATE_PO_STATUS: "PO Status Updated",
  UPDATE_PO_STATUS_VENDOR: "PO Status Updated",
  PO_VIEWED_BY_VENDOR: "PO Viewed By Vendor",
  PO_INVOICE_CREATION: "Invoice Added",
  PO_INVOICE_UPDATE: "Invoice Updated",
  PO_INVOICE_DELETE: "PO Invoice Deleted",
  PO_MFG_CREATION: "MFG Doc Added",
  PO_MFG_UPDATE: "MFG DOC Updated",
  PO_MFG_DELETED: "MFG DOC Deleted",
  PO_REJECTED: "Vendor Rejected",
  PO_ACCEPTED: "Vendor Accepted",
  PO_SEND_TO_VENDOR: "Sent PO Link To Vendor",
  PO_RESEND_TO_VENDOR: "Sent PO To Vendor",
  PO_ATTACHMENT_SENT: "Sent PO To Vendor",
  PO_ATTACHMENT_RESENT: "Sent PO To Vendor",
  VIEW_PO: "PO Viewed",
  CANCEL_PO: "PO Canceled",
  HOLD_PO: "PO Held",
  KILL_PO: "PO Killed",
  PO_LINK_CLOSED: "PO Public View Link Closed",
  ADD_COMMENT: "Comment Added",
  INVOICE_UPLOAD: "Invoice Uploaded",
  TRACKING_REQUEST: "Tracking Number Requested",
  FAILED_REQUEST: "Tracking Number Request Failure",
  SHIPPING_METHOD_UPDATE: "Shipping Method Update",
  CONTACT_PERSON_UPDATE: "Contact Person Update",
  VENDOR_UPDATE: "Vendor Update",
  PO_TYPE_UPDATE: "PO Type Update",
  PAYMENT_METHOD_UPDATE: "Payment Method Update",
  SHIPPING_ACCOUNT_UPDATE: "Shipping Account Update",
  VENDOR_BILLING_ADDRESS_UPDATE: "Vendor Billing Address Update",
  TAX_AMOUNT_UPDATE: "Tax Amount Update",
  COMMENT_UPDATE: "Comment Update",
  SHIPPING_COST_UPDATE: "Shipping Cost Update",
  INSURANCE_UPDATE: "Insurance Update",
  RECEIVING_INSTRUCTION_UPDATE: "Receiving Instruction Update",
  ORDER_UPDATE: "Order Update",
  UPDATED_BY_UPDATE: "Updated By Update",
  PRODUCT_QUANTITY_UPDATE: "Product Quantity Update",
  PRODUCT_PRICE_UPDATE: "Product Price Update",
  PRODUCT_UPDATED_BY_UPDATE: "Product Updated By Update",
  PRODUCT_DELETE: "Product Delete",
};

module.exports = {
  po_activity_type
}
