module.exports = {
    addProductController: require('./addProductController'),
    getSingleProductController: require('./getSingleProductController'),
    updateProductController: require('./updateProductController'),
    getProductListController: require('./getProductListController'),
    updateThumbnailController: require('./updateThumbnailController'),
    deleteGalleryImageController: require('./deleteGalleryImageController'),
    uploadGalleryImageController: require('./uploadGalleryImageController'),
    recentViewProductController: require('./recentViewProductController'),
    getFeaturedProductController: require('./getFeaturedProductController'),
    getRecentViewProductController: require('./getRecentViewProductController'),
    publicProductViewController: require('./publicProductViewController'),
    getSingleProductBySlugController: require('./getSingleProductBySlugController'),
    getProductsByIDsController: require('./getProductsByIDsController'),
    getOnSaleProductController: require('./getOnSaleProductController'),
}