module.exports = {
    ...require('./users'),
    ...require('./roles'),
    ...require('./admins'),
    ...require('./rolesPermission'),
    ...require('./staffs'),
    ...require('./categories'),
    ...require('./products'),
    ...require('./brands'),
    ...require('./attributeGroup'),
    ...require('./banner'),
    ...require('./attribute'),
    ...require('./customerGroup'),
    ...require('./coupon'),
    ...require('./rating'),
}