module.exports = {
    poSettingController: require('./poSettingController'),
    createPurchaseOrderController: require('./createPurchaseOrderController'),
    updatePurchaseOrderController: require('./updatePurchaseOrderController'),
    getPurchaseOrderListController: require('./getPurchaseOrderListController'),
    getSinglePurchaseOrderController: require('./getSinglePurchaseOrderController'),
    updatePOStatusController: require('./updatePOStatusController'),
    createReceivingController: require('./createReceivingController'),
    viewPurchaseOrderPublicController: require('./viewPurchaseOrderPublicController'),
    createPOTRKDetailsController: require('./createPOTRKDetailsController'),
    getPOTRKListController: require('./getPOTRKListController'),
    createPOActivityController: require('./createPOActivityController'),
    getPOActivityListController: require('./getPOActivityListController'),
    createPOInvoiceController: require('./createPOInvoiceController'),
    getPOInvoiceListController: require('./getPOInvoiceListController'),
    createMFGDOCController: require('./createMFGDOCController'),
    getPOMFGDOCListController: require('./getPOMFGDOCListController'),
    createPOStatusController: require('./createPOStatusController'),
    getPOStatusListController: require('./getPOStatusListController'),
    getPONumbersController: require('./getPONumbersController'),
}