
module.exports = {
    addOrderStatusController: require('./addOrderStatusController'),
    updateOrderStatusController: require('./updateOrderStatusController'),
    getSingleOrderStatusController: require('./getSingleOrderStatusController'),
    getOrderStatusListController: require('./getOrderStatusListController'),
    getPublicOrderStatusListController: require('./getPublicOrderStatusListController'),
    createOrderByCustomerController: require('./createOrderByCustomerController'),
    createOrderByAdminController: require('./createOrderByAdminController'),
    getOrderlistAdminController: require('./getOrderlistAdminController'),
    getSingleOrderAdminController: require('./getSingleOrderAdminController'),
    updateOrderController: require('./updateOrderController'),
    orderStatusChangeController: require('./orderStatusChangeController'),
    getOrderListByCustomerIDController: require('./getOrderListByCustomerIDController'),
    getSingleOrderCustomerController: require('./getSingleOrderCustomerController'),
    orderCancelByCustomerController: require('./orderCancelByCustomerController'),
    getOrderActivityHistoryController: require('./getOrderActivityHistoryController'),
    getOrderUpdateAdminListController: require('./getOrderUpdateAdminListController'),
    getOrderBySearchController: require('./getOrderBySearchController'),
}